name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#Почему-то работает только Residential, не подскажете почему?
flutter:
  uses-material-design: true
  fonts:
    - family: SeasonChange
      fonts:
        - asset: assets/fonts/SeasonChange.otf
    - family: Residential
      fonts:
        - asset: assets/fonts/Residential.otf
    - family: HealthyFood
      fonts:
        - asset: assets/fonts/HealthyFood.otf
  assets:
    - assets/avatar.jpeg
    - assets/curved_arrow.svg
    - assets/about_me.svg
    - assets/ball.svg
    - assets/development.svg
