name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  decimal: ^2.3.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
