name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 6.1.0
  intl: ^0.19.0
  sensors_plus: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.11


flutter:
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/images/
    - assets/fonts/
