name: surf_flutter_courses_template
description: Our courses' template.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0" # Dart SDK version
  flutter: 3.10.3 # Fixed Flutter version

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
